---
title: "Techniki Wizualizacji Danych - Projekt 2"
author: "Karol Prusinowski, Magda Tatarynowicz"
date: "5 grudnia 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)

library(ggplot2)
library(plotly)
library(dplyr)
library(rCharts)
library(scales)
library(gridExtra)
library(ggthemes)

library(tidytext)
library(knitr)
data(stop_words)
```

```{r, cache = TRUE}
library(readr)

read_text_frame <- function(title){
  text <- read_file(title)
  text_split <- unlist(strsplit(text, "\n|\t|\r"))
  text_frame <- data.frame(line = text_split)
  text_frame <- data.frame(line = as.character(text_frame[!apply(text_frame, 1, function(x) grepl("^\\s*$", x) | x == '----------'),]), stringsAsFactors=FALSE)
  text <- do.call(rbind.data.frame, apply(text_frame, 1, function(x) unlist(strsplit(x, ":"))))
  text <- text[,-3]
  colnames(text) <- c("person", "word")
  text$person <- as.character(text$person)
  text$word <- as.character(text$word)
  
  for(i in 1:nrow(text)) {
    row <- text[i,]
    if(row[1] == row[2]){
      text[i,1] <- ""
    }
    text[i,2] <- tolower(gsub('[.,!?]', '', text[i,2]))
  }
  
  # Jak chcemy mieć jedną wypowiedź na wiersz to trzeba dwie linijki poniżej usunąć
  # Teraz zostawiam słowo na wiersz
  s <- strsplit(text$word, split = " ")
  text <- data.frame(person = rep(text$person, sapply(s, length)), word = unlist(s))
  
  text %>% filter(word != "" & person != "" & !grepl("Scene", person) & person != "LOCATION")
}

read_text_frame_no_colons <- function(title) {
  text <- read_file(title)
  text_split <- unlist(strsplit(text, "\r\n"))
  text_frame <- NULL
  row <- NULL
  for (i in 1:length(text_split)) {
    line <- text_split[i]
    if(line!="" & grepl("^[A-Z\\. ]*-?[A-Z\\. ]*$", line)) {
      row$person = line
    }
    else  {
      if(line == "") {
        if(!is.null(row$person) & !is.null(row$line)) {
          text_frame <- rbind(text_frame, row)
        }
        row <- NULL
      }
      else {
        row$line = ifelse(is.null(row$line), line, paste(row$line, line))
      }
    }
  }
  
  rownames(text_frame) <- NULL
  text <- as.data.frame(text_frame, stringsAsFactors=FALSE)
  text$person <- as.character(text$person)
  text$line <- as.character(text$line)
  
  for(i in 1:nrow(text)) {
    row <- text[i,]
    if(row[1] == row[2]){
      text[i,1] <- ""
    }
    text[i,2] <- tolower(gsub('[.,!?]', '', text[i,2]))
  }

  s <- strsplit(text$line, split = " ")
  text <- data.frame(person = rep(text$person, sapply(s, length)), word = unlist(s))
  
  text
}

read_plain_text <- function(title){
  text <- read_file(title)
  text_split <- unlist(strsplit(text, "\n|\t|\r"))
  text_frame <- data.frame(line = text_split)
  text_frame <- data.frame(line = as.character(text_frame[!apply(text_frame, 1, function(x) grepl("^\\s*$", x) | x == '----------'),]), stringsAsFactors=FALSE)
  
  for(i in 1:nrow(text_frame)) {
    text_frame[i,1] <- tolower(gsub('[".,!?-]', '', text_frame[i,1]))
  }
  
  s <- strsplit(text_frame$line, split = " ")
  text <- data.frame(word = unlist(s))
  text %>% filter(word != "")
}

part1 <- read_text_frame("the Philosophers Stone.txt")
part2 <- read_text_frame("the Chamber of Secrets.txt")
part3 <- read_plain_text("the Prisoner of Azkaban transcript.txt")
part4 <- read_text_frame_no_colons("the Goblet of Fire.txt")
part5 <- read_plain_text("the Order of the Phoenix transcript.txt")
part6 <- read_plain_text("the Half Blood Prince transcript.txt")
part7 <- read_plain_text("the Deathly Hallows 1 transcript.txt")
part8 <- read_plain_text("the Deathly Hallows 2 transcript.txt")



book1 <- read_plain_text("books/the Philosophers Stone.txt")
book2 <- read_plain_text("books/the Chamber of Secrets.txt")
book3 <- read_plain_text("books/the Prisoner of Azkaban.txt")
book4 <- read_plain_text("books/the Goblet of Fire.txt")
book5 <- read_plain_text("books/the Order of the Phoenix.txt")
book6 <- read_plain_text("books/the Half Blood Prince.txt")
book7 <- read_plain_text("books/the Deathly Hallows.txt")

```

# Seria Harry Potter

## Porównanie emocji w filmach i książkach

```{r}
process_sentiment <- function(set, id, scale_max){
  sentiment <- set %>% inner_join(get_sentiments("afinn"))
  df <- data.frame(score = cumsum(sentiment$score), index = seq_along(sentiment$score), Part = id, word = sentiment$word)
  df["index_scaled"] <- rescale(df$index, to = c(0, scale_max))
  df
}

movie_scale <- 800
sentiment1 <- process_sentiment(part1, "1", movie_scale)
sentiment2 <- process_sentiment(part2, "2", movie_scale)
sentiment3 <- process_sentiment(part3, "3", movie_scale)
sentiment4 <- process_sentiment(part4, "4", movie_scale)
sentiment5 <- process_sentiment(part5, "5", movie_scale)
sentiment6 <- process_sentiment(part6, "6", movie_scale)
sentiment7 <- process_sentiment(part7, "7", movie_scale)
sentiment8 <- process_sentiment(part8, "8", movie_scale)

sentiment <- rbind(sentiment1, sentiment2, sentiment3, sentiment4,
                   sentiment5, sentiment6, sentiment7, sentiment8)

p2_movie <- ggplot() + geom_line(aes(y = score, x = index_scaled, color = Part, label = word), data = sentiment) +
  scale_colour_brewer(palette = "Paired") +  theme_minimal() +  ggtitle("Movies") +
  theme(axis.title.x=element_blank(),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank(),
        axis.title.y=element_blank(),
        axis.ticks.y=element_blank())
ggplotly(p2_movie, tooltip = c("Part", "word"))

book_scale <- 10000
sentiment_book1 <- process_sentiment(book1, "1", book_scale)
sentiment_book2 <- process_sentiment(book2, "2", book_scale)
sentiment_book3 <- process_sentiment(book3, "3", book_scale)
sentiment_book4 <- process_sentiment(book4, "4", book_scale)
sentiment_book5 <- process_sentiment(book5, "5", book_scale)
sentiment_book6 <- process_sentiment(book6, "6", book_scale)
sentiment_book7 <- process_sentiment(book7, "7", book_scale)

sentiment_book <- rbind(sentiment_book1, sentiment_book2, sentiment_book3, sentiment_book4,
                        sentiment_book5, sentiment_book6, sentiment_book7)

p2_book <- ggplot() + geom_line(aes(y = score, x = index_scaled, color = Part, label = word), data = sentiment_book) + 
    scale_colour_brewer(palette = "Paired")  +
  theme_minimal() + ggtitle("Books") + 
  theme(axis.title.x=element_blank(),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank(),
        axis.title.y=element_blank(),
        axis.ticks.y=element_blank())
ggplotly(p2_book, tooltip = c("Part", "word"))
```

## Negatywnie nacechowane słowa

```{r,results='asis',comment=NA}
count_negative_words <- function(set, negative, partNum) {
  res <- table(as.character(set$word[set$word %in% negative]))
  res <- as.data.frame(res[order(res, decreasing = TRUE)])
  colnames(res) <- c("word", "count")
  rest <- setdiff(negative, res$word)
  res <- rbind(res, data.frame(word=rest, count = rep(0,length(rest))))
  res$part <- rep(partNum, nrow(res))
  res$percentage <- 100*res$count/ nrow(set)
  res
}

negativeWords <- c("kill", "blood", "bloody", "dead", 
                   "death", "died", "killed", "crucio", 
                   "avada", "imperio", "torture", 
                   "pain", "mudblood", "hate", 
                   "murder", "murderer", "killing", 
                   "bleeding", "sectumsempra", "damn",
                   "bitch", "git", "die", "hell", 
                   "harm", "hell", "panic", "afraid",
                   "evil", "worry", "attack")

negative1 <- count_negative_words(part1, negativeWords, 1)
negative2 <- count_negative_words(part2, negativeWords, 2)
negative3 <- count_negative_words(part3, negativeWords, 3)
negative4 <- count_negative_words(part4, negativeWords, 4)
negative5 <- count_negative_words(part5, negativeWords, 5)
negative6 <- count_negative_words(part6, negativeWords, 6)
negative7 <- count_negative_words(part7, negativeWords, 7)
negative8 <- count_negative_words(part8, negativeWords, 8)

negative <- rbind(negative1, negative2, negative3, negative4,
                  negative5, negative6, negative7, negative8)


p = nPlot(percentage ~ part, group =  "word", data = negative, type = 'stackedAreaChart')
p$chart(useInteractiveGuideline=TRUE)
p$print(include_assets=T)


negative_book1 <- count_negative_words(book1, negativeWords, 1)
negative_book2 <- count_negative_words(book2, negativeWords, 2)
negative_book3 <- count_negative_words(book3, negativeWords, 3)
negative_book4 <- count_negative_words(book4, negativeWords, 4)
negative_book5 <- count_negative_words(book5, negativeWords, 5)
negative_book6 <- count_negative_words(book6, negativeWords, 6)
negative_book7 <- count_negative_words(book7, negativeWords, 7)

negative_book <- rbind(negative_book1, negative_book2, negative_book3, negative_book4,
                  negative_book5, negative_book6, negative_book7)


p = nPlot(percentage ~ part, group =  "word", data = negative_book, type = 'stackedAreaChart')
p$chart(useInteractiveGuideline=TRUE)
p$print(include_assets=T)
```

